const scheduleData = [
  {
    day: "Monday",
    date: "4",
    color: "bg-red-400",
    classes: [
      {
        subject: "Financial Accounting",
        time: "8:00 AM - 9:30 AM",
        teacher: "Prof. James Blackwood",
        location: "Room 220, Business Building",
        type: "Lecture",
        tagColor: "bg-red-500",
      },
      {
        subject: "Business Analytics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 205, Business Building",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
         {
        subject: "Business Analytics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 205, Business Building",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
         {
        subject: "Business Analytics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 205, Business Building",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
         {
        subject: "Business Analytics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 205, Business Building",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
         {
        subject: "Business Analytics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 205, Business Building",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
      {
        subject: "Microeconomics",
        time: "2:00 PM - 3:30 PM",
        teacher: "Dr. Emily Thompson",
        location: "Room 310, Economics Wing",
        type: "Tutorial",
        tagColor: "bg-gray-600",
      },
    ],
  },
  {
    day: "Tuesday",
    date: "2",
    color: "bg-green-500",
    classes: [
      {
        subject: "Marketing Fundamentals",
        time: "8:00 AM - 9:30 AM",
        teacher: "Prof. Michael Torres",
        location: "Room 115, Business Building",
        type: "Online",
        tagColor: "bg-green-500",
      },
      {
        subject: "Business Statistics",
        time: "10:00 AM - 11:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 310, Business Building",
        type: "Seminar",
        tagColor: "bg-yellow-500",
      },
    ],
  },
  {
    day: "Wednesday",
    date: "4",
    color: "bg-pink-500",
    classes: [
      {
        subject: "Financial Accounting",
        time: "8:00 AM - 9:30 AM",
        teacher: "Dr. Sarah Chen",
        location: "Room 220, Business Building",
        type: "Online",
        tagColor: "bg-green-500",
      },
      {
        subject: "Business Analytics",
        time: "10:30 AM - 11:30 AM",
        teacher: "Prof. Chen",
        location: "Room 205, Business Building",
        type: "Seminar",
        tagColor: "bg-yellow-500",
      },
      {
        subject: "Microeconomics",
        time: "1:00 PM - 2:30 PM",
        teacher: "Dr. Emily Thompson",
        location: "Room 310, Economics Wing",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
    ],
  },
  {
    day: "Thursday",
    date: "3",
    color: "bg-blue-500",
    classes: [
      {
        subject: "Financial Accounting",
        time: "8:00 AM - 9:30 AM",
        teacher: "Prof. James Blackwood",
        location: "Room 220, Business Building",
        type: "Tutorial",
        tagColor: "bg-gray-600",
      },
      {
        subject: "Microeconomics",
        time: "1:00 PM - 2:30 PM",
        teacher: "Dr. Emily Thompson",
        location: "Room 310, Economics Wing",
        type: "Hybrid",
        tagColor: "bg-blue-500",
      },
      {
        subject: "Leadership & Communication",
        time: "3:00 PM - 4:30 PM",
        teacher: "Dr. Williams",
        location: "Room 305, Business Wing",
        type: "Seminar",
        tagColor: "bg-yellow-500",
      },
    ],
  },
  {
    day: "Friday",
    date: "2",
    color: "bg-purple-500",
    classes: [
      {
        subject: "Financial Accounting",
        time: "8:00 AM - 9:30 AM",
        teacher: "Prof. James Blackwood",
        location: "Room 220, Business Building",
        type: "Seminar",
        tagColor: "bg-yellow-500",
      },
      {
        subject: "Microeconomics",
        time: "1:00 PM - 2:30 PM",
        teacher: "Dr. Emily Thompson",
        location: "Room 310, Economics Wing",
        type: "Tutorial",
        tagColor: "bg-gray-600",
      },
    ],
  },
];

export default scheduleData;
